src/cart/urls.py
from django.urls import path, include
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:pk>', views.cart_add, name='cart_add'),
    path('remove/<int:pk>', views.cart_remove, name='cart_remove'),
]

src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls.conf import include



urlpatterns = [
    path('s-admin/', admin.site.urls),
    path('', include('references.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('accounts/', include('accounts.urls', namespace='accounts')),              
]

src/references/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.contrib import admin
from accounts import urls 
from orders import urls

app_name = 'shop'

urlpatterns = [
    
    path('', views.HomePage.as_view(), name='home'),
    path('catalog/', views.ProductView.as_view(), name='catalog'),
    path('catalog/<int:id>', views.product_detail, name='product'),
    #path('catalog/<int:pk>', views.ProductDetail.as_view(), name='product'),
    path('catalog-delete/<int:pk>', views.ProductDelete.as_view(), name='catalog-delete'),
    path('product-create/', views.ProductCreate.as_view(), name='product-create'),
    path('catalog-update/<int:pk>', views.ProductUpdate.as_view(), name='product-update'),

    
    #path('dashboard/', include(account_urls)),

    path('author/', views.AuthorView.as_view(), name='author'),
    path('author/<int:pk>', views.AuthorDetail.as_view(), name='author-page'),
    path('author-delete/<int:pk>', views.AuthorDelete.as_view(), name='author-delete'),
    path('author-create/', views.AuthorCreate.as_view(), name='author-create'),
    path('author-update/<int:pk>', views.AuthorUpdate.as_view(), name='author-update'),

    path('genre/', views.GenreView.as_view(), name='genre'),
    path('genre/<int:pk>', views.GenreDetail.as_view(), name='genre-page'),
    path('genre-delete/<int:pk>', views.GenreDelete.as_view(), name='genre-delete'),
    path('genre-create/', views.GenreCreate.as_view(), name='genre-create'),
    path('genre-update/<int:pk>', views.GenreUpdate.as_view(), name='genre-update'),

    path('publisher/', views.PublisherView.as_view(), name='publisher'),
    path('publisher/<int:pk>', views.PublisherDetail.as_view(), name='publisher-page'),
    path('publisher-delete/<int:pk>', views.PublisherDelete.as_view(), name='publisher-delete'),
    path('publisher-create/', views.PublisherCreate.as_view(), name='publisher-create'),
    path('publisher-update/<int:pk>', views.PublisherUpdate.as_view(), name='publisher-update'),

    path('series/', views.SeriesView.as_view(), name='series'),
    path('series/<int:pk>', views.SeriesDetail.as_view(), name='series-page'),
    path('series-delete/<int:pk>', views.SeriesDelete.as_view(), name='series-delete'),
    path('series-create/', views.SeriesCreate.as_view(), name='series-create'),
    path('series-update/<int:pk>', views.SeriesUpdate.as_view(), name='series-update'),

    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

src/references/models.py
from django.db import models


# Create your models here.

class Author(models.Model):
    
    name_author = models.CharField(
        verbose_name ='Автор',
        max_length=50)
    desc_author = models.TextField(
        verbose_name ='Краткая информация об авторе',
        max_length=50,
        null=True,
        blank=True)

    def __str__(self):
        return self.name_author
    
    class Meta:
        verbose_name = 'Автор'
        verbose_name_plural = 'Авторы'



class Series(models.Model):
    name_series = models.CharField(
        verbose_name ='Серия',
        max_length=50)

    desc_series = models.TextField(
        verbose_name ='Краткая информация о серии',
        max_length=50,
        null=True,
        blank=True)

    def __str__(self):
        return self.name_series

    class Meta:
        verbose_name = 'Серия'
        verbose_name_plural = 'Серии'

class Publisher(models.Model):
    name_publisher = models.CharField(
        verbose_name ='Издатель',
        max_length=50)

    desc_publisher = models.TextField(
        verbose_name ='Краткая информация об Издателе',
        max_length=50,
        null=True,
        blank=True)

    def __str__(self):
        return self.name_publisher
    class Meta:
        verbose_name = 'Издатель'
        verbose_name_plural = 'Издатели'
class Genre(models.Model):
    name_genre = models.CharField(
        verbose_name ='Жанр',
        max_length=50)
        
    desc_genre = models.TextField(
        verbose_name ='Краткая информация о Жанре',
        max_length=50,
        null=True,
        blank=True)
    def __str__(self):
        return self.name_genre

    class Meta:
        verbose_name = 'Жанр'
        verbose_name_plural = 'Жанры'

class Product(models.Model):
    name_product = models.CharField(
        verbose_name ='Название книги',
        max_length=80)
    author = models.ManyToManyField(
        'Author',
        verbose_name ='Автор')
    serie = models.ForeignKey(
        'Series',
        verbose_name ='Серия',
        on_delete=models.PROTECT,
        blank=True,
        null=True)
    genre = models.ManyToManyField(
        'Genre',
        verbose_name ='Жанр'
    )
    year = models.CharField(
        verbose_name ='Год издания'
        ,max_length=50,
        blank=True,
        null=True)
    pages = models.IntegerField(
        verbose_name ='Страниц',
        blank=True,
        null=True)
    cover = models.CharField(
        verbose_name ='Переплет',
        max_length=50,
        blank=True,
        null=True)
    format = models.ForeignKey(
        'Formats',
        on_delete=models.PROTECT,
        verbose_name ='Формат',
        null=True)
    isbn = models.CharField(
        verbose_name ='ISBN',
        max_length=50,
        blank=True,
        null=True)  
    weight = models.IntegerField(
        verbose_name='Вес(гр)',
        blank=True,
        null=True)
    age_restrict = models.CharField(
        verbose_name='Возрастные ограничения',
        max_length=50,
        null=True)
    publisher = models.ForeignKey(
        'Publisher',
        verbose_name ='Издатель',
        on_delete=models.PROTECT,
        blank=True,
        null=True)
    price = models.DecimalField(
        max_digits=10, 
        decimal_places=2,
        verbose_name ='Цена',
        null=True)
    created = models.DateTimeField(
        verbose_name ='Создано',
        auto_now=False,
        null=True)
    updated = models.DateTimeField(
        verbose_name ='Обновлено',
        auto_now=True,
        null=True)
    image = models.ImageField(
        null=True,
        blank = True,
        upload_to = 'image/',
        default='http://placehold.it/700x400'
    )
    def __str__(self):
        return self.name_product

    class Meta:
        verbose_name = 'Книга'
        verbose_name_plural = 'Книги'


class Formats(models.Model):
    name_format = models.CharField(
        verbose_name ='Название формата',
        max_length=80)
    desc_format = models.TextField(
        verbose_name ='Описание формата',
        null=True,
        blank = True)
        
    def __str__(self):
        return self.name_format

    class Meta:
        verbose_name = 'Формат'
        verbose_name_plural = 'Форматы'

src/references/forms.py
from django import forms
from django.db.models import fields
from . import models

class ProductForm(forms.ModelForm):

    class Meta:
        model = models.Product
        fields = ('name_product','price')

class AuthorForm(forms.ModelForm):

    class Meta:
        model = models.Author
        fields = ('name_author','desc_author')

class GenreForm(forms.ModelForm):

    class Meta:
        model = models.Genre
        fields = ('name_genre','desc_genre')

class PublisherForm(forms.ModelForm):

    class Meta:
        model = models.Publisher
        fields = ('name_publisher','desc_publisher')

class SeriesForm(forms.ModelForm):

    class Meta:
        model = models.Series
        fields = ('name_series','desc_series')

src/references/views.py
from django.http.response import Http404, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.urls.base import reverse_lazy
from .models import Author, Product, Series, Publisher, Genre
from . import forms
from cart.forms import CartAddProductForm
from django.shortcuts import get_object_or_404
from django.views.generic import DetailView, ListView, DeleteView, CreateView, UpdateView, TemplateView

# Create your views here.
def index(request):
    products = Product.objects.all()
    context = {'products' : products}
    return render(request, 'references/index.html', context)

class IndexList(ListView):
    model=Product

class HomePage(TemplateView):
    model = Product
    template_name = "references/homepage.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        products = self.model.objects.all().order_by('-pk')
        context['objects'] = products
        return context

def shop(request):
    products = Product.objects.all()
    context = {'products' : products}
    return render(request, 'references/shop.html', context)

class ProductView(ListView):
    model=Product
    template_name_suffix='_list'



def product_page(request, pk):
    product = Product.objects.get(pk=pk)
    context = {'object' : product, 'pk': pk}
    return render(request, 'references/product_page.html', context)

class ProductDetail(DetailView):
    model=Product
    template_name_suffix='_page'



def product_delete(request, pk):
    product = Product.objects.get(pk=pk)
    message = f'Продукт {product.name_product} удален'
    product.delete()
    context = {'message' : message}
    return render(request, 'references/product_delete.html', context)

class ProductDelete(DeleteView):
    success_url= reverse_lazy('catalog')
    model=Product
    

def product_create(request):
    context = {}
    if request.method == 'POST':
        form = forms.ProductForm(request.POST)
        if form.is_valid():
            product = form.save()
            return HttpResponseRedirect(reverse('product', kwargs={'pk':product.pk}))
        else:
            context['form'] = form
    else:
        context['form'] = forms.ProductForm()
    
    return render(request, 'references/product_create.html', context)

class ProductCreate(CreateView):
    success_url=reverse_lazy('catalog')
    model=Product
    fields=('name_product','price')

def product_update(request, pk):
    context = {}
    if request.method == 'GET':
        product = Product.objects.get(pk=pk)
        context = {'product': product}
    elif request.method == 'POST':
        name_product = request.POST.get('name_product')
        price = request.POST.get('price')
        product = Product.objects.get(pk=pk)
        product.name_product=name_product
        product.price=price
        product.save()

        return HttpResponseRedirect(reverse('product', kwargs={'pk':product.pk}))
    return render(request, 'references/product_update.html', context)

class ProductUpdate(UpdateView):
    success_url=reverse_lazy('catalog')
    model=Product
    fields=('name_product','price')
    template_name_suffix='_update_form'

class AuthorView(ListView):
    model=Author
    template_name_suffix='_list'
    paginate_by = 2
    queryset = Author.objects.all()

class AuthorDetail(DetailView):
    model=Author
    template_name_suffix='_page'

class AuthorDelete(DeleteView):
    success_url= reverse_lazy('author')
    model=Author


class AuthorCreate(CreateView):
    success_url=reverse_lazy('author')
    model=Author
    fields=('name_author','desc_author')

class AuthorUpdate(UpdateView):
    success_url=reverse_lazy('author')
    model=Author
    fields=('name_author','desc_author')
    template_name_suffix='_update_form'


#genre cbv
class GenreView(ListView):
    model=Genre
    template_name_suffix='_list'

class GenreDetail(DetailView):
    model=Genre
    template_name_suffix='_page'

class GenreDelete(DeleteView):
    success_url= reverse_lazy('genre')
    model=Genre


class GenreCreate(CreateView):
    success_url=reverse_lazy('genre')
    model=Genre
    fields=('name_genre')

class GenreUpdate(UpdateView):
    success_url=reverse_lazy('genre')
    model=Genre
    fields=('name_genre','desc_genre')
    template_name_suffix='_update_form'
    
#publisher

class PublisherView(ListView):
    model=Publisher
    template_name_suffix='_list'

class PublisherDetail(DetailView):
    model=Publisher
    template_name_suffix='_page'

class PublisherDelete(DeleteView):
    success_url= reverse_lazy('publisher')
    model=Publisher


class PublisherCreate(CreateView):
    success_url=reverse_lazy('publisher')
    model=Publisher
    fields=('name_publisher','desc_publisher')

class PublisherUpdate(UpdateView):
    success_url=reverse_lazy('publisher')
    model=Publisher
    fields=('name_publisher')
    template_name_suffix='_update_form'

#serie

#publisher

class SeriesView(ListView):
    model=Series
    template_name_suffix='_list'

class SeriesDetail(DetailView):
    model=Series
    template_name_suffix='_page'

class SeriesDelete(DeleteView):
    success_url= reverse_lazy('series')
    model=Series


class SeriesCreate(CreateView):
    success_url=reverse_lazy('series')
    model=Series
    fields=('name_series','desc_series')

class SeriesUpdate(UpdateView):
    success_url=reverse_lazy('series')
    model=Series
    fields=('name_series','desc_series')
    template_name_suffix='_update_form'


#class DashboardView():



#

def product_detail(request, id):
    product = get_object_or_404(Product, id=id)
    cart_product_form = CartAddProductForm()
    context = {
        'product': product,
        'cart_product_form': cart_product_form
    }
    print(context)
    return render(request, 'references/product_page.html', context)

src/references/templates/references/author_confirm_delete.html
{% extends 'references/base.html'%}

{% block title %}
Удаление Автора
{% endblock %}


{% block content %}

<div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light">
    <div class="col-md-5 p-lg-5 mx-auto my-5">
      <h1 class="display-5 font-weight-normal">Удаление Автора</h1>
      <form action="" method="POST">
        {% csrf_token %}
        <button class="btn btn-danger">Точно удалить?</button>
      </form>
    </div>
    <div class="product-device box-shadow d-none d-md-block"></div>
    <div class="product-device product-device-2 box-shadow d-none d-md-block"></div>
  </div>
    <h1></h1>
{% endblock %} 

src/references/templates/references/genre_confirm_delete.html
{% extends 'references/base.html'%}

{% block title %}
Удаление Автора
{% endblock %}


{% block content %}

<div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light">
    <div class="col-md-5 p-lg-5 mx-auto my-5">
      <h1 class="display-5 font-weight-normal">Удаление Автора</h1>
      <form action="" method="POST">
        {% csrf_token %}
        <button class="btn btn-danger">Точно удалить?</button>
      </form>
    </div>
    <div class="product-device box-shadow d-none d-md-block"></div>
    <div class="product-device product-device-2 box-shadow d-none d-md-block"></div>
  </div>
    <h1></h1>
{% endblock %} 

src/references/templates/references/genre_list.html
{% extends 'references/base.html'%}

{% block title %}
Авторы
{% endblock %}

{% block content %}
        <div class="row">
            
          {% for el in object_list %}
          
          <div class="col-lg-4 col-md-6 mb-4">
            <div class="card h-100">
              {% if el.image.url %}
                <a href="{% url 'genre' el.pk %}"><img class="card-img-top" src="{{ el.image.url }}"></a>
              {% else %}
                <a href="{{el.id}}"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
              {% endif %}
              <div class="card-body">
                <h4 class="card-title">
                  <a href="{{el.id}}">{{ el.name_genre }}</a>
                  
                </h4>
                
                <!-- {% for elem in el.author.all %}
                <p class="card-text">{{ elem }}</p>
                {% endfor %}  -->
                <h5>{{ el.desc_author }} </h5>
                <!--<h5>{{ el.created  }}</h5>-->
              </div>
              <!--<div class="card-footer">
                <small class="text-muted">★ ★ ★ ★ ☆</small>
              </div>-->
            </div>
          </div>
          {% endfor %}  
        </div>

  
{% endblock %}

src/references/templates/references/genre_page.html
{% extends 'references/base.html'%}

{% block title %}
{{ object.name_product }}
{% endblock %}


{% block content %}

<div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light">
    <div class="col-md-5 p-lg-5 mx-auto my-5">
      {% if object.image.url %}
        <img class="card-img-top" src="{{ object.image.url }}">
      {% else %}
        <img class="card-img-top" src="http://placehold.it/700x400" alt="">
      {% endif %}
      <h1 class="display-5 font-weight-normal">{{ object.name_genre }}</h1>
      <h2 class="display-5 font-weight-normal">{{ object.desc_author }} </h1><br>
      {% for elem in object.author.all %}
      <p class="lead font-weight-normal">{{ elem }}</p>
      {% endfor %}
      <a class="btn btn btn-secondary" href="{% url 'genre' %}">Обратно к Жанрам</a><br><br>
      <a class="btn btn btn-success" href="{% url 'genre-create' %}">Добавить Жанр</a>
      <a class="btn btn btn-primary" href="{% url 'genre-update' object.pk %}">Обновить Жанр</a><br><br>
      <a class="btn btn btn-danger" href="{% url 'genre-delete' object.pk %}">Удалить</a>
    </div>
    <div class="product-device box-shadow d-none d-md-block"></div>
    <div class="product-device product-device-2 box-shadow d-none d-md-block"></div>
  </div>
    <h1></h1>
{% endblock %} 

src/references/templates/references/genre_update_form.html
{% extends 'references/base.html'%}

{% block title %}
Обновление
{% endblock %}


{% block content %}

<div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light">
    <div class="col-md-5 p-lg-5 mx-auto my-5">
      <h1 class="display-5 font-weight-normal">Обновление Автора</h1>
      <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-outline-primary">Изменить</button>
      </form>
    </div>
    <div class="product-device box-shadow d-none d-md-block"></div>
    <div class="product-device product-device-2 box-shadow d-none d-md-block"></div>
  </div>
    <h1></h1>
{% endblock %} 

src/references/templates/references/homepage.html
{% extends 'references/base.html'%}
{% load crispy_forms_tags %}

{% block content %}
<h1>Новинки</h1>
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    {% for object in objects %}
    <div class="carousel-item {% if object == objects.0 %}active{% endif %}">
      <div class="card mb-3 border-light text-dark container-fluid" style="max-width: 480px; text-align: center;">
        <div class="row g-0">
          <div class="col-md-4">
          {% if object.image %}
            <a href="{% url 'shop:product' object.pk %}"><img class="card-img-top" src="{{ object.image.url }}"></a>
            {% else %}
            <a href="{{object.id}}"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
          {% endif %}
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <a href="{% url 'shop:product' object.pk %}"><h5 class="card-title">{{ object.name_product }}</h5></a>
              {% for elem in object.author.all %}
              <p class="card-text">{{ elem }}</p>
              {% endfor %}
              <div class="price">{{ object.price }} BYN</div>

              <p class="card-text"><small class="text-muted">
                <a href="{% url 'shop:product' object.pk %}" class="btn btn-success btn-sm text-bottom"></i>Подробнее</a>
              </small></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  {% endfor %}
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <i class="fa fa-angle-left" style="font-size:48px;color:grey"></i>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <i class="fa fa-angle-right" style="font-size:48px;color:grey"></i>
  </a>
</div>
      
{% endblock %}

src/references/templates/references/product_confirm_delete.html
{% extends 'references/base.html'%}

{% block title %}
Удаление
{% endblock %}


{% block content %}

<div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light">
    <div class="col-md-5 p-lg-5 mx-auto my-5">
      <h1 class="display-5 font-weight-normal">Удаление книги</h1>
      <form action="" method="POST">
        {% csrf_token %}
        <button class="btn btn-danger">Точно удалить?</button>
      </form>
    </div>
    <div class="product-device box-shadow d-none d-md-block"></div>
    <div class="product-device product-device-2 box-shadow d-none d-md-block"></div>
  </div>
    <h1></h1>
{% endblock %} 

src/references/templates/references/product_delete.html
{% extends 'references/base.html'%}

{% block title %}
Удаление Книги
{% endblock %}


{% block content %}

<div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light">
    <div class="col-md-5 p-lg-5 mx-auto my-5">
      <h1 class="display-5 font-weight-normal">{{ message }}</h1>
    </div>
    <div class="product-device box-shadow d-none d-md-block"></div>
    <div class="product-device product-device-2 box-shadow d-none d-md-block"></div>
  </div>
    <h1></h1>
{% endblock %} 

src/references/templates/references/product_detail.html
{% extends 'references/base.html'%}

{% block title %}
{{ object.name_product }}
{% endblock %}


{% block content %}

<div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light">
    <div class="col-md-5 p-lg-5 mx-auto my-5">
      <h1 class="display-5 font-weight-normal">{{ object.name_product }}</h1>
      <h2 class="display-5 font-weight-normal">{{ object.price }} BYN</h1><br>
      {% for elem in object.author.all %}
      <p class="lead font-weight-normal">{{ elem }}</p>
      {% endfor %}
      <p class="price">${{ product.price }}</p>
      <form action="{% url 'cart:cart_add' product.id %}" method="post">
          {{ cart_product_form }}
          {% csrf_token %}
          <input type="submit" value="Add to cart">
      </form>
      <a class="btn btn btn-secondary" href="{% url 'catalog' %}">Обратно в магазин</a><br><br>
      <a class="btn btn btn-success" href="{% url 'product-create' %}">Добавить товар</a>
      <a class="btn btn btn-primary" href="{% url 'product-update' object.pk %}">Обновить товар</a><br><br>
      <a class="btn btn btn-danger" href="{% url 'catalog-delete' object.pk %}">Удалить</a>
    </div>
    <div class="product-device box-shadow d-none d-md-block"></div>
    <div class="product-device product-device-2 box-shadow d-none d-md-block"></div>
  </div>
    <h1></h1>
{% endblock %} 

src/references/templates/references/product_form.html
{% extends 'references/base.html'%}

{% block title %}
Создание
{% endblock %}


{% block content %}

<div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light">
    <div class="col-md-5 p-lg-5 mx-auto my-5">
      <h1 class="display-5 font-weight-normal">Добавление книги</h1>
      <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-outline-primary">Добавить</button>
      </form>
    </div>
    <div class="product-device box-shadow d-none d-md-block"></div>
    <div class="product-device product-device-2 box-shadow d-none d-md-block"></div>
  </div>
    <h1></h1>
{% endblock %} 

src/references/templates/references/publisher_form.html
{% extends 'references/base.html'%}

{% block title %}
Создание Издательства
{% endblock %}


{% block content %}

<div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light">
    <div class="col-md-5 p-lg-5 mx-auto my-5">
      <h1 class="display-5 font-weight-normal">Добавление Издательства</h1>
      <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-outline-primary">Добавить</button>
      </form>
    </div>
    <div class="product-device box-shadow d-none d-md-block"></div>
    <div class="product-device product-device-2 box-shadow d-none d-md-block"></div>
  </div>
    <h1></h1>
{% endblock %} 

src/references/templates/references/series_form.html
{% extends 'references/base.html'%}

{% block title %}
Создание Серии
{% endblock %}


{% block content %}

<div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light">
    <div class="col-md-5 p-lg-5 mx-auto my-5">
      <h1 class="display-5 font-weight-normal">Добавление Серии</h1>
      <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-outline-primary">Добавить</button>
      </form>
    </div>
    <div class="product-device box-shadow d-none d-md-block"></div>
    <div class="product-device product-device-2 box-shadow d-none d-md-block"></div>
  </div>
    <h1></h1>
{% endblock %} 

src/references/templates/references/series_list.html
{% extends 'references/base.html'%}

{% block title %}
Серии
{% endblock %}

{% block content %}

        <div class="row">
            
          {% for el in object_list %}
          
          <div class="col-lg-4 col-md-6 mb-4">
            <div class="card h-100">
              {% if el.image.url %}
                <a href="{% url 'series' el.pk %}"><img class="card-img-top" src="{{ el.image.url }}"></a>
              {% else %}
                <a href="{{el.id}}"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
              {% endif %}
              <div class="card-body">
                <h4 class="card-title">
                  <a href="{{el.id}}">{{ el.name_series }}</a>
                  
                </h4>
                
                <!-- {% for elem in el.author.all %}
                <p class="card-text">{{ elem }}</p>
                {% endfor %}  -->
                <h5>{{ el.desc_author }} </h5>
                <!--<h5>{{ el.created  }}</h5>-->
              </div>
              <!--<div class="card-footer">
                <small class="text-muted">★ ★ ★ ★ ☆</small>
              </div>-->
            </div>
          </div>
          {% endfor %}  
        </div>

{% endblock %}

src/references/templates/references/series_page.html
{% extends 'references/base.html'%}

{% block title %}
{{ object.name_product }}
{% endblock %}


{% block content %}

<div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light">
    <div class="col-md-5 p-lg-5 mx-auto my-5">
      {% if object.image.url %}
        <img class="card-img-top" src="{{ object.image.url }}">
      {% else %}
        <img class="card-img-top" src="http://placehold.it/700x400" alt="">
      {% endif %}
      <h1 class="display-5 font-weight-normal">{{ object.name_series }}</h1>
      <h2 class="display-5 font-weight-normal">{{ object.desc_author }} </h1><br>
      {% for elem in object.author.all %}
      <p class="lead font-weight-normal">{{ elem }}</p>
      {% endfor %}
      <a class="btn btn btn-secondary" href="{% url 'series' %}">Обратно к Сериям</a><br><br>
      <a class="btn btn btn-success" href="{% url 'series-create' %}">Добавить Серию</a>
      <a class="btn btn btn-primary" href="{% url 'series-update' object.pk %}">Обновить Сeрию</a><br><br>
      <a class="btn btn btn-danger" href="{% url 'series-delete' object.pk %}">Удалить</a>
    </div>
    <div class="product-device box-shadow d-none d-md-block"></div>
    <div class="product-device product-device-2 box-shadow d-none d-md-block"></div>
  </div>
    <h1></h1>
{% endblock %} 