src/cart/urls.py
from django.urls import path, include
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:pk>', views.cart_add, name='cart_add'),
    path('remove/<int:pk>', views.cart_remove, name='cart_remove'),
]

src/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('order-summary', views.OrderSummaryView.as_view(),name='order-summary'),
]

src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls.conf import include



urlpatterns = [
    path('s-admin/', admin.site.urls),
    path('', include('references.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('accounts/', include('accounts.urls', namespace='accounts')),              
]

src/references/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.contrib import admin
from accounts import urls 
from orders import urls

app_name = 'shop'

urlpatterns = [
    
    path('', views.HomePage.as_view(), name='home'),
    path('catalog/', views.ProductView.as_view(), name='catalog'),
    path('catalog/<int:id>', views.product_detail, name='product'),
    #path('catalog/<int:pk>', views.ProductDetail.as_view(), name='product'),
    path('catalog-delete/<int:pk>', views.ProductDelete.as_view(), name='catalog-delete'),
    path('product-create/', views.ProductCreate.as_view(), name='product-create'),
    path('catalog-update/<int:pk>', views.ProductUpdate.as_view(), name='product-update'),

    
    #path('dashboard/', include(account_urls)),

    path('author/', views.AuthorView.as_view(), name='author'),
    path('author/<int:pk>', views.AuthorDetail.as_view(), name='author-page'),
    path('author-delete/<int:pk>', views.AuthorDelete.as_view(), name='author-delete'),
    path('author-create/', views.AuthorCreate.as_view(), name='author-create'),
    path('author-update/<int:pk>', views.AuthorUpdate.as_view(), name='author-update'),

    path('genre/', views.GenreView.as_view(), name='genre'),
    path('genre/<int:pk>', views.GenreDetail.as_view(), name='genre-page'),
    path('genre-delete/<int:pk>', views.GenreDelete.as_view(), name='genre-delete'),
    path('genre-create/', views.GenreCreate.as_view(), name='genre-create'),
    path('genre-update/<int:pk>', views.GenreUpdate.as_view(), name='genre-update'),

    path('publisher/', views.PublisherView.as_view(), name='publisher'),
    path('publisher/<int:pk>', views.PublisherDetail.as_view(), name='publisher-page'),
    path('publisher-delete/<int:pk>', views.PublisherDelete.as_view(), name='publisher-delete'),
    path('publisher-create/', views.PublisherCreate.as_view(), name='publisher-create'),
    path('publisher-update/<int:pk>', views.PublisherUpdate.as_view(), name='publisher-update'),

    path('series/', views.SeriesView.as_view(), name='series'),
    path('series/<int:pk>', views.SeriesDetail.as_view(), name='series-page'),
    path('series-delete/<int:pk>', views.SeriesDelete.as_view(), name='series-delete'),
    path('series-create/', views.SeriesCreate.as_view(), name='series-create'),
    path('series-update/<int:pk>', views.SeriesUpdate.as_view(), name='series-update'),

    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

src/cart/models.py
from django.db import models
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey

# Create your models here.

src/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, label='Количество')
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

src/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from references.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, pk):
    cart = Cart(request)
    product = get_object_or_404(Product, pk=pk)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')



def cart_remove(request, pk):
    cart = Cart(request)
    product = get_object_or_404(Product, pk=pk)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})

src/cart/templates/cart/detail.html
{% extends 'references/base.html'%}
{% load static %}
{% block title %}
    Корзина
{% endblock %}
{% block content %}
    <h1>Корзина</h1>
    {% if cart %}  
    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col"></th>
            <th scope="col">Товар</th>
            <th scope="col">Количество</th>
            
            <th scope="col">Цена</th>
            <th scope="col">Сумма</th>
            <th scope="col"></th>
        </tr>
        </thead>
        <tbody>
         
        {% for item in cart %}
            {% with product=item.product %}
                <tr>
                    <td style="width: 10%">
                        <a href="{{ product.get_absolute_url }}">
                            <img src="
                                {% if product.image %}
                                    {{ product.image.url }}
                                {% else %}
                                    -
                                {% endif %}" style="width:50px;">
                        </a>
                    </td>
                    <td class="td-cart">{{ product.name_product }}</td>
                    <td class="td-cart">{{ item.quantity }}</td>
                    
                    <td class="num td-cart">{{ item.price }}</td>
                    <td class="num td-cart">{{ item.total_price }}</td>
                    <td class="td-cart"><a href="{% url 'cart:cart_remove' product.pk%}" class="delete__link"><i class="fa fa-trash" aria-hidden="true"></i></a></td>
                </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Итого</td>
            <td colspan="4"></td>
            <td class="num">{{ cart.get_total_price }}</td>
        </tr>
        </tbody>
    </table>
    
    <p class="text-right">
        <a href="{% url 'shop:catalog' %}" class="btn btn-light">Продолжить покупки</a>
        <a href="{% url 'orders:order_create' %}" class="btn btn-success">Оформить заказ</a>
    </p>
    {% else %}
        <div class="">Ваша корзина пуста</div>
    <p class="text-center">
        <a href="{% url 'shop:catalog' %}" class="btn btn-light">В магазин</a>
    </p>
    {% endif %}

    
{% endblock %}